### PR TITLE
Some reorganization

### PR DESCRIPTION
**Pull request by yeesian**
to separate the following

1. user-facing convenience functions (in `src/proj_functions.jl`)
2. the low-level wrapper functions (in `src/proj_capi.jl`)
3. type definitions (in `src/proj_types.jl`)

The module file (`src/Proj4.jl`) itself should be primarily for
organizing imports/exports/versioning-cruft.

### CODE REVIEW

**Comment by yeesian** [comment]
Hm, I might have borked the commit history for some reason? Can never seem to figure out how it works with git.

**Comment by c42f** [comment]
Ah, the confusion might be because I rebased your previous set of changes before adding a couple more and merging back to master.  If you just rebase your reorg branch on top of FugroRoames/master and force push that should fix things.

**Comment by yeesian** [comment]
Ah okay, I just checked https://github.com/FugroRoames/Proj4.jl/network and it seems fine. I'm ready for a review of the changes here, and had already begun on a separate `geod` branch off this one last night, haha.

**Comment by c42f** [comment]
Thanks, I assume you closed this by mistake?  Will probably have some to look through later today.

**Comment by yeesian** [comment]
nope; it turned out to be a bigger effort than i anticipated. See #4

**Comment by c42f** [comment]
Right, missed that somehow.

**Pull request closed without merging**
