### PR TITLE
Parse version into Base.VersionNumber

### PR DESCRIPTION
**Pull request by c42f**
Replace version() with a const VersionNumber, and use this to conditionally include the geodesic functionality.

### CODE REVIEW

**Comment by c42f** [comment]
@yeesian - some tweaks to version testing if you'd like to look.

**Comment by yeesian** [comment]
LGTM. I like how it doesn't litter variables all over, the way I did

**Comment by c42f** [comment]
cheers

**Comment by c42f** [comment]
Ugh, looks like I missed a couple of things.  I pushed another minor change to clean up versioning.  In particular, looks like the geod library functions are available for 4.9.0 and greater.

**Comment by yeesian** [comment]
feel free to push straight to master

**Comment by c42f** [comment]
Done - they're very minor fixes.

**Pull request merged**
